### PR TITLE
Soft clip for duplication

### PR DESCRIPTION
**Pull request by msahraeian**
Added soft-clip analysis and assembly capability for Tandem Duplications. To avoid noisy predictions form other methods we only perform assembly if Soft-clip has been detected for the interval.

### CODE REVIEW

**Comment by marghoob** [comment]
Thanks. Do we have some numbers on this one? By the way, just to be clear, this assembly would only work for tandem duplications. For interspersed duplications, ITX-style assembly approach may be required.

**Comment by msahraeian** [comment]
Yes. I assumed the DUP are back to back. Out of 3 FN in the paper, we could detect 2 with SC, so we have 2 more TP (SEN:88.9, PRECISON:90.9, F1:89.9)

**Comment by marghoob** [comment]
Thanks. We may need to handle interspersed duplication assembly since the soft-clip analysis can identify them as well as CNVnator.

**Comment by msahraeian** [comment]
Do we have interspersed duplication in the Varsim data?

**Comment by marghoob** [comment]
No. VarSim does not support interspersed dups. That again is something we could consider adding to VarSim.

**Comment by msahraeian** [comment]
I have some ideas for detecting interspersed dups and ITX, but not sure if I should implement it on this merge or not as I cannot test it on Varsim data.

**Comment by marghoob** [comment]
This pull request is okay-we can do interspersed dups separately.

**Pull request closed without merging**
