### PR TITLE
Support for Lumpy, Manta and CNVkit

### PR DESCRIPTION
**Pull request by chapmanb**
Marghoob and John;
Thanks for all the great work on MetaSV and for making it available. Inspired by your presentation at the Genome in a Bottle call, we migrated MetaSV into bcbio (https://github.com/chapmanb/bcbio-nextgen) and added support for Lumpy, Manta and CNVkit. We validated the implementation against the Genome in a Bottle NA12878 calls as well as synthetic dataset 3 from the ICGC-TCGA DREAM challenge (https://www.synapse.org/#!Synapse:syn312572/wiki/) and the results look great:

http://imgur.com/a/Gajsg

We're planning to replace the simple ensemble approach we previously used in bcbio with MetaSV thanks to encouragement from @bioinfo and @mjafin.

This PR contains a few additions and fixes to MetaSV that enable this:

- Support for ingesting VCF files from Manta, Lumpy and CNVkit. This uses the current command line syntax by adding new flags, although it might be helpful to generalize this in the future to avoid having so many options.
- Filter out SVs larger than the maximum size during the initial VCF reading process. Without this in place larger SVs will merge with smaller SVs they contain, and the smaller SVs drop out of downstream merging and reassembly. If you have any large spurious calls these will wipe out sensitivity in those regions. This avoids that by removing these earlier in the process. 
- Fixes to support the latest PyVCF, which uses objects for the ALT alleles instead of raw strings.
- Avoid use of `timeout -k` which is not present on CentOS systems, when running SPAdes.

Please let me know if you have any questions. Thanks again.

### CODE REVIEW

**Comment by marghoob** [comment]
Hi @chapmanb ,

Thanks for this work which includes not only new tools but also some bugfixes/enhancements! We appreciate this a lot and are pretty excited about the bcbio integration. Below are some comments and questions:
* From the looks of it, the results for MetaSV were generated by integrating from LUMPY, Manta and CNVkit, right?
* It would also be helpful to compare against the MetaSV results without LUMPY, Manta, CNVkit integration to see the impact of this change. That would require it to have been run with the results from Pindel, BreakDancer, BreakSeq2 and CNVnator. If you do not have these for NA12878 Illumina Platinum sample, we can definitely share the MetaSV output for that with you. 
* Did you include all MetaSV calls or just the PASS ones for comparison?
* The precision seems low, especially for larger SVs. So, it would be good to have a look at the outputs from your comparison to improve the quality of results especially on the precision of the calls.

Best,
Marghoob.

**Comment by chapmanb** [comment]
Marghoob;
Thanks for the quick response. You're right, this comparison is from MetaSV with Lumpy, Manta and CNVkit. We don't have support in bcbio for any of the other callers MetaSV works with (which was why I hadn't tried MetaSV to this point) so I don't have a clean way to test those. Practically the only change that has any impact on results in the earlier removal of large SV elements, so you could test that separately if you have worries. The other changes are mechanics for the new callers and fixes.

The validation uses the PASS results from MetaSV only for the comparison. I think there are places to improve and happy to work on these over time. For the NA12878 large regions, I'd imagine this could partially be due to unreported events in the truth set, as this isn't seen as much in the synthetic results from the DREAM challenge (although they also don't have events quite as big).

Thanks again and let me know if there is anything that would be helpful for merging in this set of changes.

**Comment by marghoob** [comment]
Brad,

Thanks for your response. I think we can do a quick assessment of the impact if you can send us the MetaSV output for NA12878 from your integration and we can then compare with the MetaSV results using the original 4 tools on NA12878 platinum data. By the way, did you also enable assembly for your MetaSV run? I also see this pull request referenced in bcbio and understand that you are trying to integrate it in bcbio. Do you know when the integration would be complete?

Thanks again for your interest and help!

Best,
Marghoob.

**Comment by chapmanb** [comment]
Marghoob;
Here are the NA12878 calls from the MetaSV run with Manta, Lumpy and CNVkit run within bcbio:

https://s3.amazonaws.com/bcbio/metasv/NA12878-metasv-vcf.gz

Definitely let me know if you notice any issues or discrepancies. This was run with assembly using SPAdes and AGE.

MetaSV works in the development version of bcbio right now. We install SPAdes and AGE along with a conda package of MetaSV from my patched branch. If you add `svcaller: [lumpy, manta, cnvkit, metasv]` to the algorithm configuration it will work without any additional changes. I'm happy to have this going and looking forward to contributing more on improving it as we continue to do more validation work. Thanks again.

**Comment by marghoob** [comment]
Thanks, Brad. Let me have a look at the VCF from you. We appreciate the
bcbio integration very much and are excited to have this collaboration
going on and also helping to improve SV-calling in the process!

Best,
Marghoob.

On Tue, Aug 11, 2015 at 7:10 PM, Brad Chapman <notifications@github.com>
wrote:

> Marghoob;
> Here are the NA12878 calls from the MetaSV run with Manta, Lumpy and
> CNVkit run within bcbio:
>
> https://s3.amazonaws.com/bcbio/metasv/NA12878-metasv-vcf.gz
>
> Definitely let me know if you notice any issues or discrepancies. This was
> run with assembly using SPAdes and AGE.
>
> MetaSV works in the development version of bcbio right now. We install
> SPAdes and AGE along with a conda package of MetaSV from my patched branch.
> If you add svcaller: [lumpy, manta, cnvkit, metasv] to the algorithm
> configuration it will work without any additional changes. I'm happy to
> have this going and looking forward to contributing more on improving it as
> we continue to do more validation work. Thanks again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioinform/metasv/pull/55#issuecomment-130136381>.
>



-- 

<http://www.bina.com>

*Marghoob Mohiyuddin, PhD  *//  Sr. Bioinformatics Scientist, Bina
Technologies, part of Roche Sequencing
E. marghoob@bina.com

*Learn More*  //  video <http://www.bina.com/product.html>  //  news
<http://www.bina.com/press-coverage.html>  //  posters
<http://f1000.com/posters/search?query=bina+technologies>  //  science
<http://www.bina.com/science.html>  //  platform
<http://www.bina.com/platform.html>
*Test Drive Bina  //  Experience NextGen analysis for yourself *
<http://www.bina.com/test-drive.html>

**Comment by marghoob** [comment]
Hi @chapmanb ,

Apologies for the delay. I compared against the MetaSV deletion calls generated by using the original 4 tools on the NA12878 Illumina Platinum genomes sample (let's call this Bina MetaSV). For the baseline, the GiaB deletions were used. The SV size cutoff was set to 100bp since MetaSV has poor performance below 100bp. 2348 deletions from GiaB SVs made this cutoff. Of these, Bina MetaSV (which had 2671 PASS calls) missed 181 calls, giving a sensitivity of 92.3% while bcbio MetaSV (which had 3789 PASS calls) missed 151 calls giving a sensitivity of 93.6%, which is good. However, the number of private calls for bcbio MetaSV is 1598 in comparison to 511 from Bina MetaSV, suggesting potentially higher false discovery rate. I also found that of these 1598 calls, 826 calls were still missing in the Bina MetaSV calls for the NA12878's parents, which again reinforces the hypothesis of higher FDR. It would also, therefore, be useful if you can share the bcbio MetaSV calls for the parents of NA12878 to better assess the improvement. I am thinking of still merging this one and then working with you on further assessments as well improvements in bcbio. Please let me know what you think. I also looking forward to meeting you at the GiaB workshop.

Best,
Marghoob.

**Comment by chapmanb** [comment]
Marghoob;
Thanks so much for looking in depth at this. I'm 100% agreed with your assessment of MetaSV with Lumpy, Manta and CNVkit -- it improved sensitivity over any of the callers but with a loss of precision.

We'd need to put time into identifying false positives with Lumpy, Manta and CNVkit and seeing if we can resolve the MetaSV filtering to deal with those. Your current implementation likely reflects the large amoutn of time you put into doing this for the existing callers, so is tuned to the unique idiosyncrasies of those.

I'm happy to work on this. I saw this pull request as a first step getting the mechanics working, and then we can continue to iterate and improve on it, so I totally agree with your plan.

I'm bummed I won't be able to make it to the GiaB workshop this year, so won't get to meet you in person. I'm going to do my best to follow remotely to try to keep up. Thanks again for working on this.

**Comment by marghoob** [comment]
Thanks a lot, Brad. We are looking forward to continued collaboration. Due to some recent changes made by us, we are seeing merge conflict in .gitignore. Could you please fix this tiny conflict and then I will merge this pull request?

**Comment by chapmanb** [comment]
Marghoob -- Thanks so much. I pulled in the upstream changes so this should be clean and ready to go again.

**Comment by marghoob** [comment]
Thanks @chapmanb . Just merged the pull request and created a new release for MetaSV. Cheers!

**Pull request merged**
