### PR TITLE
SEQ-7330: Fix broken dependencies.

### PR DESCRIPTION
**Pull request by sbandara**
This fix addresses two recent issues that are introduced by external dependencies:
- When MetaSV is run with a more recent version of pybedtools (>= 0.7.0), SAMtools fails with a `TypeError` "Expected bytes, got unicode". This is because pybedtools returns unicode strings that promote certain strings in MetaSV, one of which is then passed to SAMtools.
- Execution of SPAdes and AGE is broken on Mac OS X (return value is 127) because `timeout` is not available on that platform.

This PR includes:
- A fix for the unicode bug. The unicode string is converted to a byte string.
- A new class `TimedExternalCmd` which is used for executing SPAdes and AGE under a timeout, but without platform-specific dependencies, so that it works both on Linux and Mac OS X.
- Various unit tests for `TimedExternalCmd`.

I validated this PR (a) in conjunction with #85 and AGE from abyzov/age/master, and (b) as-is but with AGE from marghoob/age/simple-parseable-output. The test case is that from #85.

### CODE REVIEW

**Comment by marghoob** [comment]
Thanks a lot. This resolves a long-standing feature add I had in mind!

**Comment by marghoob** [comment]
@sbandara is this okay to merge?

**Comment by sbandara** [comment]
I tested this comprehensively on Mac OS X. However, I was wondering if you have some process similar to the seqalto repository whereby someone *different* will review as well and vote before merge? Maybe @johnmu or @msahraeian? @msahraeian, did you combine this with #85 when you tested on Debian? 

By the way, should we think about having a separate develop branch for future PRs?

**Comment by msahraeian** [comment]
No. I just tested #85. Do you want me to test this too?

**Comment by sbandara** [comment]
I am fixing merge conflicts with #82 right now in the massive parallelization PR that I am preparing. I will test that upcoming PR in conjunction with #85 on Debian. But if you could test #85 pulled into your local master as well, that would be very valuable.

**Comment by marghoob** [comment]
@sbandara due to the paucity of Python coders, it was only I and @msahraeian reviewing code. Since you are also involved now, we have enough people to review the code and can employ a manner similar to the seqalto repository. Given that this is a small project as of now and in the near future, I am okay with PRs into the master branch for now. @msahraeian, when you are done testing, let us know and I will merge this PR.

**Comment by johnmu** [comment]
oh I learnt a new word `paucity` :D

**Comment by sbandara** [comment]
Cool, thanks everyone! Doing simple tests on a new SEQ-7207_parallel_assembly branch after resolving with #82, then opening PR against master.

**Comment by msahraeian** [comment]
I tested #86 and it is good to go.

**Comment by marghoob** [comment]
Thanks, @msahraeian! @sbandara is it okay to merge this one now?

**Comment by sbandara** [comment]
Yes, let's do it. Many thanks!

**Pull request merged**
